Repository Heongilee/projectTeam, pull requests merged in 2021-09, with the labels that each got.

#96 Security config :: api refresh, setting security config
  therapist/src/main/java/com/projectTeam/therapist/boardService/ReplyService.java
  therapist/src/main/java/com/projectTeam/therapist/configuration/WebSecurityConfig.java
  therapist/src/main/java/com/projectTeam/therapist/repository/ReplyRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/ReplyApiController.java
  therapist/src/main/java/com/projectTeam/therapist/restService/UserApiController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/AccountController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
Labels: 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️

#101 feature/userService-authController :: userService/AuthController.java…
  therapist/build.gradle
  therapist/src/main/java/com/projectTeam/therapist/userService/AuthController.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️

#102 feature/userService-authController :: userService/AuthController.java…
  therapist/build.gradle
  therapist/src/main/java/com/projectTeam/therapist/userService/AuthController.java
Labels: 완성✅

#105 feature/apiUpdate-findByPostId :: postId로 글 조회하기에서 사용자등급 속성 추가 + 특정 답…
  therapist/src/main/java/com/projectTeam/therapist/boardService/ReplyService.java
  therapist/src/main/java/com/projectTeam/therapist/postService/CommentService.java
  therapist/src/main/java/com/projectTeam/therapist/postService/PostService.java
  therapist/src/main/java/com/projectTeam/therapist/restService/ReplyApiController.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️, 유라_확인🙆🏻‍♀️

#106 feature/mypagePageable :: 마이페이지 postType별 pageable 기능 삭제
  .idea/compiler.xml
  .idea/runConfigurations.xml
  therapist/src/main/java/com/projectTeam/therapist/configuration/WebConfig.java
  therapist/src/main/java/com/projectTeam/therapist/repository/PostCommentRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/PostRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/ReplyCommentRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/ReplyRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/MyPageApiController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️

#108 Feature/kakao logout :: kakao Logout 설정 및 menuType별 반환 데이터 최종
  client/src/hook/useKakao.js
  therapist/src/main/java/com/projectTeam/therapist/restService/UserApiController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️

#109 feature/openVidu :: openvidu media server 구성 변경
  openvidu-insecure-react/.gitignore
  openvidu-insecure-react/package-lock.json
  openvidu-insecure-react/src/App.js
Labels: 완성✅, 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️, 유라_확인🙆🏻‍♀️

#113 redux saga websocket
  client/src/App.js
  client/src/_actions/loading_actions.js
  client/src/_actions/types.js
  client/src/_actions/user_actions.js
  client/src/_reducers/loading_reducer.js
  client/src/_reducers/user_reducer.js
  client/src/api/api.js
  client/src/components/AnswerForm/AnswerForm.js
  client/src/components/CommentField/CommentField.js
  client/src/components/LoadingBar/LoadingBar.js
  client/src/components/MyPageForm/MyPageForm.js
  client/src/components/Pagination/PaginationCmp.js
  client/src/components/QuestionForm/QuestionForm.js
  client/src/components/SelectCard/SelectCard.css
  client/src/components/StarButton/StarButton.js
  client/src/config/confing.js
  client/src/constants/myPageConstants.js
  client/src/hook/useBoard.js
  client/src/hook/useBoardState.js
  client/src/hook/useCheckBox.js
  client/src/hook/useCheckBoxModal.js
  client/src/hook/useComment.js
  client/src/hook/useKakao.js
  client/src/hook/useModal.js
  client/src/hook/useQuery.js
  client/src/hook/useStar.js
  client/src/pages/ErrorPage/ErrorPage.css
  client/src/pages/ErrorPage/ErrorPage.js
  client/src/pages/Mypage/MyPage.css
  client/src/pages/Mypage/Mypage.js
  client/src/pages/PostPage/PostPage.js
  client/src/pages/WritePage/WritePage.js
  client/src/pages/WritePage/helper/requestApi.js
  client/src/sagas/createSocketChannel.js
  client/src/sagas/index.js
  client/src/sagas/loadingSaga.js
  client/src/sagas/loginSaga.js
  client/src/sagas/socketSaga.js
  client/src/utils/ErrorHandler.js
  client/src/utils/modalCase.js
Labels: 완성✅, 헌기_확인🙆🏻‍♂️, 유라_확인🙆🏻‍♀️

#115 feature/notice :: 사용자 알림 API 구현
  therapist/src/main/java/com/projectTeam/therapist/boardService/ReplyService.java
  therapist/src/main/java/com/projectTeam/therapist/model/NoticeDto.java
  therapist/src/main/java/com/projectTeam/therapist/postService/CommentService.java
  therapist/src/main/java/com/projectTeam/therapist/postService/NoticeService.java
  therapist/src/main/java/com/projectTeam/therapist/repository/NoticeRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/NoticeApiController.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️

#116 feature/find session :: 특정 사용자 세션에 notice message 보내기
  client/src/hook/useComment.js
  client/src/pages/WritePage/WritePage.js
  client/src/sagas/createSocketChannel.js
  therapist/src/main/java/com/projectTeam/therapist/notice/ReplyEchoHandler.java
Labels: 검토 중👨🏻‍💻, 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️

#118 Feature/fixApi :: API수정 및 기능 변경
  therapist/src/main/java/com/projectTeam/therapist/boardService/ReplyService.java
  therapist/src/main/java/com/projectTeam/therapist/model/NoticeDto.java
  therapist/src/main/java/com/projectTeam/therapist/model/PostCommentDto.java
  therapist/src/main/java/com/projectTeam/therapist/model/ReplyCommentDto.java
  therapist/src/main/java/com/projectTeam/therapist/postService/CommentService.java
  therapist/src/main/java/com/projectTeam/therapist/postService/NoticeService.java
  therapist/src/main/java/com/projectTeam/therapist/postService/PostService.java
  therapist/src/main/java/com/projectTeam/therapist/repository/NoticeRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/PostCommentRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/PostRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/ReplyCommentRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/ReplyRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/ReplyApiController.java
  therapist/src/main/java/com/projectTeam/therapist/restService/UserApiController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️

#119 Feature/noticePageable :: Notice API 수정
  therapist/src/main/java/com/projectTeam/therapist/boardService/ReplyService.java
  therapist/src/main/java/com/projectTeam/therapist/model/NoticeDto.java
  therapist/src/main/java/com/projectTeam/therapist/postService/CommentService.java
  therapist/src/main/java/com/projectTeam/therapist/postService/NoticeService.java
  therapist/src/main/java/com/projectTeam/therapist/repository/NoticeRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/NoticeApiController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/AuthController.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️

#120 Feature/react open vidu code
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/api/api.js
  client/src/api/openViduApi.js
  client/src/api/postApi.js
  client/src/components/AnswerForm/AnswerForm.js
  client/src/components/Atoms/InputField/InputField.js
  client/src/components/Header/Sections/NavBarSection/RightMenu.css
  client/src/components/Header/Sections/NavBarSection/RightMenu.js
  client/src/components/InfiniteArea/InfiniteArea.js
  client/src/components/LoadingBar/LoadingBar.js
  client/src/components/Modal/ModalWriteForm.js
  client/src/components/PopOverContent/PopOverContent.css
  client/src/components/PopOverContent/PopOverContent.js
  client/src/components/SpinLoadIcon/SpinLoadIcon.css
  client/src/components/SpinLoadIcon/SpinLoadIcon.js
  client/src/config/confing.js
  client/src/constants/modalConstants.js
  client/src/constants/noticeConstants.js
  client/src/constants/writePageConstants.js
  client/src/hook/useAnswer.js
  client/src/hook/useBoardState.js
  client/src/hook/useCheckBoxModal.js
  client/src/hook/useComment.js
  client/src/hook/useInfiniteScroll.js
  client/src/hook/useKakao.js
  client/src/hook/useModal.js
  client/src/hook/useNotice.js
  client/src/hook/useOpenVidu.js
  client/src/hook/usePushMessage.js
  client/src/hook/useWriteModal.js
  client/src/pages/BoardPage/BoardPage.js
  client/src/pages/MainPage/MainPage.js
  client/src/pages/MainPage/sections/CardSection.css
  client/src/pages/MainPage/sections/CardSection.js
  client/src/pages/NoticePage/NoticePage.css
  client/src/pages/NoticePage/NoticePage.js
  client/src/pages/PostPage/AnswerArea.js
  client/src/pages/PostPage/PostPage.js
  client/src/pages/WebRtcPage/WebCard.css
  client/src/pages/WebRtcPage/WebCard.js
  client/src/pages/WebRtcPage/WebRtcPage.css
  client/src/pages/WebRtcPage/WebRtcPage.js
  client/src/pages/WritePage/WritePage.js
  client/src/sagas/createSocketChannel.js
  client/src/sagas/index.js
  client/src/sagas/loadingSaga.js
  client/src/sagas/socketSaga.js
  client/src/utils/modalCase.js
  client/webpack.config.js
Labels: 검토 중👨🏻‍💻, 헌기_확인🙆🏻‍♂️, 유라_확인🙆🏻‍♀️

#121 Feature/react open vidu code
  client/src/App.js
  client/src/api/api.js
  client/src/components/Modal/Modal.css
  client/src/components/Modal/ModalRedio.js
  client/src/components/Modal/ModalRoomCreate.js
  client/src/config/confing.js
  client/src/context/openViduContext.js
  client/src/hook/useContextOpv.js
  client/src/hook/useOpenVidu.js
  client/src/hook/useRedioModal.js
  client/src/hook/useVoiceRoom.js
  client/src/index.css
  client/src/pages/OpenViduPage/OpenViduPage.css
  client/src/pages/OpenViduPage/OpenViduPage.js
  client/src/pages/OpenViduPage/sections/GridCard.css
  client/src/pages/OpenViduPage/sections/GridCard.js
  client/src/pages/OpenViduPage/sections/GridLayout.css
  client/src/pages/OpenViduPage/sections/GridLayout.js
  client/src/pages/OpenViduPage/sections/OpenViduFooter.css
  client/src/pages/OpenViduPage/sections/OpenViduFooter.js
  client/src/pages/OpenViduPage/sections/OpenViduLayout.js
  client/src/pages/OpenViduPage/sections/OpenViduVideo.js
  client/src/pages/OpenViduPage/sections/SideBarCard.css
  client/src/pages/OpenViduPage/sections/SideBarCard.js
  client/src/pages/OpenViduPage/sections/SideBarLayout.css
  client/src/pages/OpenViduPage/sections/SideBarLayout.js
Labels: 헌기_확인🙆🏻‍♂️, 유라_확인🙆🏻‍♀️

#122 Feature/react open vidu code
  client/src/api/openViduApi.js
  client/src/components/Header/Sections/NavBarSection/RightMenu.js
  client/src/components/PopOverContent/PopOverContent.css
  client/src/components/PopOverContent/PopOverContent.js
  client/src/config/confing.js
  client/src/context/openViduContext.js
  client/src/hook/useCreateRoom.js
  client/src/hook/useOpenVidu.js
  client/src/hook/useVoiceRoom.js
  client/src/index.js
  client/src/pages/MainPage/MainPage.js
  client/src/pages/OpenViduPage/OpenViduPage.js
  client/src/pages/OpenViduPage/sections/OpenViduFooter.js
  client/src/pages/WebRtcPage/WebCard.css
  client/src/pages/WebRtcPage/WebCard.js
  client/src/pages/WebRtcPage/WebRtcPage.css
  client/src/pages/WebRtcPage/WebRtcPage.js
Labels: 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️

#125 Feature/openvidu session
  therapist/src/main/java/com/projectTeam/therapist/boardService/ReplyService.java
  therapist/src/main/java/com/projectTeam/therapist/configuration/WebSecurityConfig.java
  therapist/src/main/java/com/projectTeam/therapist/model/SessionDto.java
  therapist/src/main/java/com/projectTeam/therapist/openviduService/SessionService.java
  therapist/src/main/java/com/projectTeam/therapist/repository/SessionRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/OpenviduApiController.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️

#128 feature/openviduSession-hotfix :: REST API 키값 오타 수정 + CORS 에러 해결(api/…
  therapist/src/main/java/com/projectTeam/therapist/configuration/WebSecurityConfig.java
  therapist/src/main/java/com/projectTeam/therapist/openviduService/SessionService.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️
