Repository Heongilee/projectTeam, pull requests merged in 2021-08, with the labels that each got.

#34 boardpage 기능 및 api
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/_actions/board_actions.js
  client/src/_actions/types.js
  client/src/_reducers/board_reducer.js
  client/src/_reducers/index.js
  client/src/api/boardApi.js
  client/src/components/Pagination/PaginationCmp.js
  client/src/components/SideBar/SideBar.js
  client/src/components/WriteButton/WriteButton.js
  client/src/hook/useBoard.js
  client/src/index.js
  client/src/pages/BoardPage/BoardPage.js
  client/src/pages/BoardPage/sections/Posts.js
  client/src/pages/TextPage/Sections/AnswerSection.js
  client/src/pages/TextPage/TextPage.js
  client/src/setupProxy.js
  client/webpack.config.js
Labels: 완성이요🙆🏻‍♂️

#35 feature-apiMyPage :: 마이페이지에서 내가 쓴 게시글 조회 API + 내가 쓴 댓글 조회 API
  therapist/src/main/java/com/projectTeam/therapist/repository/PostCommentRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/PostRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/MyPageApiController.java
  therapist/src/main/java/com/projectTeam/therapist/restService/PostApiController.java
  therapist/src/main/java/com/projectTeam/therapist/restService/UserApiController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
Labels: 완성이요🙆🏻‍♂️

#36 feature-mainPage :: 가장 최근에 작성한 게시글 TOP 6 출력 + 내가 쓴 게시글 조회 API 수정 완료
  therapist/src/main/java/com/projectTeam/therapist/boardService/PostController.java
  therapist/src/main/java/com/projectTeam/therapist/model/PostDto.java
  therapist/src/main/java/com/projectTeam/therapist/model/UserDto.java
  therapist/src/main/java/com/projectTeam/therapist/postService/PostService.java
  therapist/src/main/java/com/projectTeam/therapist/repository/PostRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/PostApiController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
Labels: 완성이요🙆🏻‍♂️

#38 feature-delegatingService :: 리팩토링 + 일부 API들 수정.
  therapist/src/main/java/com/projectTeam/therapist/boardService/BoardService.java
  therapist/src/main/java/com/projectTeam/therapist/boardService/BoardServiceImpl.java
  therapist/src/main/java/com/projectTeam/therapist/model/CommentDto.java
  therapist/src/main/java/com/projectTeam/therapist/postService/CommentService.java
  therapist/src/main/java/com/projectTeam/therapist/postService/PostService.java
  therapist/src/main/java/com/projectTeam/therapist/repository/CommentRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/CommentApiController.java
  therapist/src/main/java/com/projectTeam/therapist/restService/Greeting.java
  therapist/src/main/java/com/projectTeam/therapist/restService/GreetingController.java
  therapist/src/main/java/com/projectTeam/therapist/restService/UserApiController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
Labels: 완성이요🙆🏻‍♂️

#44 feature-addThumbnailAvatar
  therapist/src/main/java/com/projectTeam/therapist/boardService/ReplyService.java
  therapist/src/main/java/com/projectTeam/therapist/configuration/WebSecurityConfig.java
  therapist/src/main/java/com/projectTeam/therapist/model/CustomUserDetails.java
  therapist/src/main/java/com/projectTeam/therapist/userService/AccountController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/AuthController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/CustomUserDetailsService.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
  therapist/src/main/resources/templates/fragments/common.html
Labels: 문제가 생겼어요🤦🏻‍♂️

#49 feature/webRtc_socketIo :: 주석 (#48)
  zoomClone/server.js
Labels: 검토 필요🙋🏻‍♂️

#59 Feature/web rtc chat with websocket
  client/out/projectteam/1.0.0/fonts/OpenSans-Bold-webfont.eot
  client/out/projectteam/1.0.0/fonts/OpenSans-Bold-webfont.svg
  client/out/projectteam/1.0.0/fonts/OpenSans-Bold-webfont.woff
  client/out/projectteam/1.0.0/fonts/OpenSans-BoldItalic-webfont.eot
  client/out/projectteam/1.0.0/fonts/OpenSans-BoldItalic-webfont.svg
  client/out/projectteam/1.0.0/fonts/OpenSans-BoldItalic-webfont.woff
  client/out/projectteam/1.0.0/fonts/OpenSans-Italic-webfont.eot
  client/out/projectteam/1.0.0/fonts/OpenSans-Italic-webfont.svg
  client/out/projectteam/1.0.0/fonts/OpenSans-Italic-webfont.woff
  client/out/projectteam/1.0.0/fonts/OpenSans-Light-webfont.eot
  client/out/projectteam/1.0.0/fonts/OpenSans-Light-webfont.svg
  client/out/projectteam/1.0.0/fonts/OpenSans-Light-webfont.woff
  client/out/projectteam/1.0.0/fonts/OpenSans-LightItalic-webfont.eot
  client/out/projectteam/1.0.0/fonts/OpenSans-LightItalic-webfont.svg
  client/out/projectteam/1.0.0/fonts/OpenSans-LightItalic-webfont.woff
  client/out/projectteam/1.0.0/fonts/OpenSans-Regular-webfont.eot
  client/out/projectteam/1.0.0/fonts/OpenSans-Regular-webfont.svg
  client/out/projectteam/1.0.0/fonts/OpenSans-Regular-webfont.woff
  client/out/projectteam/1.0.0/index.html
  client/out/projectteam/1.0.0/scripts/linenumber.js
  client/out/projectteam/1.0.0/scripts/prettify/Apache-License-2.0.txt
  client/out/projectteam/1.0.0/scripts/prettify/lang-css.js
  client/out/projectteam/1.0.0/scripts/prettify/prettify.js
  client/out/projectteam/1.0.0/styles/jsdoc-default.css
  client/out/projectteam/1.0.0/styles/prettify-jsdoc.css
  client/out/projectteam/1.0.0/styles/prettify-tomorrow.css
  zoomClone2/.gitignore
  zoomClone2/package.json
  zoomClone2/src/public/js/app.js
  zoomClone2/src/server.js
  zoomClone2/src/views/home.pug
Labels: 검토 필요🙋🏻‍♂️, 문제가 생겼어요🤦🏻‍♂️

#53 feature/jwt :: JWT 토큰 이용하여 사용자 정보 조회
  .idea/compiler.xml
  therapist/build.gradle
  therapist/src/main/java/com/projectTeam/therapist/configuration/WebSecurityConfig.java
  therapist/src/main/java/com/projectTeam/therapist/jwt/JwtAccessDeniedHandler.java
  therapist/src/main/java/com/projectTeam/therapist/jwt/JwtAuthenticationEntryPoint.java
  therapist/src/main/java/com/projectTeam/therapist/jwt/JwtFilter.java
  therapist/src/main/java/com/projectTeam/therapist/jwt/JwtSecurityConfig.java
  therapist/src/main/java/com/projectTeam/therapist/jwt/TokenProvider.java
  therapist/src/main/java/com/projectTeam/therapist/model/LoginDto.java
  therapist/src/main/java/com/projectTeam/therapist/model/RoleDto.java
  therapist/src/main/java/com/projectTeam/therapist/model/TokenDto.java
  therapist/src/main/java/com/projectTeam/therapist/model/UserDto.java
  therapist/src/main/java/com/projectTeam/therapist/repository/AuthorityRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/UserRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/UserApiController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/AccountController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/AuthController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/CustomUserDetailsService.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
  therapist/src/main/java/com/projectTeam/therapist/util/SecurityUtil.java
Labels: 헌기_확인🙆🏻‍♂️

#63 feature/jwt :: jwt 토큰 적용 및 grade API 구현
  .idea/compiler.xml
  therapist/build.gradle
  therapist/src/main/java/com/projectTeam/therapist/boardService/ReplyService.java
  therapist/src/main/java/com/projectTeam/therapist/configuration/WebSecurityConfig.java
  therapist/src/main/java/com/projectTeam/therapist/jwt/JwtAccessDeniedHandler.java
  therapist/src/main/java/com/projectTeam/therapist/jwt/JwtAuthenticationEntryPoint.java
  therapist/src/main/java/com/projectTeam/therapist/jwt/JwtFilter.java
  therapist/src/main/java/com/projectTeam/therapist/jwt/JwtSecurityConfig.java
  therapist/src/main/java/com/projectTeam/therapist/jwt/TokenProvider.java
  therapist/src/main/java/com/projectTeam/therapist/model/LoginDto.java
  therapist/src/main/java/com/projectTeam/therapist/model/RoleDto.java
  therapist/src/main/java/com/projectTeam/therapist/model/TokenDto.java
  therapist/src/main/java/com/projectTeam/therapist/model/UserDto.java
  therapist/src/main/java/com/projectTeam/therapist/repository/AuthorityRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/UserRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/ReplyApiController.java
  therapist/src/main/java/com/projectTeam/therapist/restService/UserApiController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/AccountController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/AuthController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/CustomUserDetailsService.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
  therapist/src/main/java/com/projectTeam/therapist/util/SecurityUtil.java
Labels: 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️, 유라_확인🙆🏻‍♀️

#68 feature/apiRefresh-postComments :: 특정 게시글(postId)에 대한 댓글(postComments…
  therapist/src/main/java/com/projectTeam/therapist/postService/CommentService.java
  therapist/src/main/java/com/projectTeam/therapist/restService/CommentApiController.java
Labels: 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️, 유라_확인🙆🏻‍♀️

#71 develop ← feature/notice :: websocket 이용하여 세션간 통신
  therapist/build.gradle
  therapist/src/main/java/com/projectTeam/therapist/configuration/WebSecurityConfig.java
  therapist/src/main/java/com/projectTeam/therapist/configuration/WebSocketConfig.java
  therapist/src/main/java/com/projectTeam/therapist/notice/ReplyEchoHandler.java
  therapist/src/main/resources/static/js/index.js
  therapist/src/main/resources/templates/index.html
Labels: 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️

#73 Feature/api refresh
  therapist/src/main/java/com/projectTeam/therapist/postService/CommentService.java
  therapist/src/main/java/com/projectTeam/therapist/repository/PostCommentRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/ReplyCommentRepository.java
  therapist/src/main/java/com/projectTeam/therapist/repository/ReplyRepository.java
  therapist/src/main/java/com/projectTeam/therapist/restService/CommentApiController.java
Labels: 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️, 유라_확인🙆🏻‍♀️

#80 feature/webRtc-modifyConsoleLog :: console.log() 수정
  zoomClone2/src/public/js/app.js
Labels: 완성✅, 헌기_확인🙆🏻‍♂️

#91 Feature/login :: 카카오 로그인과 동시에 jwt Token 담아 프론트로 보내기
  client/src/components/Header/Sections/NavBarSection/RightMenu.js
  therapist/src/main/java/com/projectTeam/therapist/configuration/WebConfig.java
  therapist/src/main/java/com/projectTeam/therapist/userService/AuthController.java
  therapist/src/main/java/com/projectTeam/therapist/userService/UserService.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️

#95 feature/apiPosts-sendByPostId :: postId에 해당하는 글 조회(/api/posts/{postId…
  .idea/compiler.xml
  .idea/runConfigurations.xml
  therapist/src/main/java/com/projectTeam/therapist/postService/PostService.java
  therapist/src/main/java/com/projectTeam/therapist/restService/PostApiController.java
Labels: 완성✅, 헌기_확인🙆🏻‍♂️, 성진_확인🙆🏻‍♂️, 유라_확인🙆🏻‍♀️
